"""empty message

Revision ID: 00b9a3a54163
Revises: a35df037ee5d
Create Date: 2017-08-26 19:54:25.122000

"""

# revision identifiers, used by Alembic.
revision = '00b9a3a54163'
down_revision = 'a35df037ee5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('comment_counter', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('like_counter', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'like_counter')
    op.drop_column('answers', 'comment_counter')
    ### end Alembic commands ###
