"""empty message

Revision ID: 240e4a67544b
Revises: 
Create Date: 2017-08-07 20:46:50.044000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '240e4a67544b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('test')
    op.add_column('users', sa.Column('reg_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=320),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=320),
               nullable=True)
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'reg_time')
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('roles')
    # ### end Alembic commands ###
