"""empty message

Revision ID: 90606cfe2911
Revises: 00b9a3a54163
Create Date: 2017-09-08 18:43:39.612000

"""

# revision identifiers, used by Alembic.
revision = '90606cfe2911'
down_revision = '00b9a3a54163'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('like_counter', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'like_counter')
    ### end Alembic commands ###
